---
- name: Create VMware Cluster
  hosts: myvcenter01.myhomelab.local  # or the appropriate host/group
  gather_facts: yes  # Set to yes if you need to gather facts

  tasks:
    - name: Create Cluster
      vmware.vmware.cluster:
        hostname: myvcenter01.myhomelab.local
        username: root
        password: VMware1!
        datacenter_name: datacenter
        cluster_name: hellocluster
