---
- name: Test VMware API Connection
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: Test vCenter API connection
      vmware.vmware.vmware_rest:
        hostname: 192.168.2.121
        username: administrator@vsphere.local
        password: VMware1!
        validate_certs: no

    - name: Create VMware Cluster
      vmware.vmware.cluster:
        hostname: 192.168.2.121
        username: administrator@vsphere.local
        password: VMware1!
        datacenter_name: datacenter
        cluster_name: hellocluster
        validate_certs: no
