---
- name: Gather cluster info from given datacenter
  hosts: myvcenter01.myhomelab.local  # or the appropriate host/group
  gather_facts: yes  # Set to yes if you need to gather facts

  tasks:
    - name: CreatingCluster
      community.vmware.vmware_cluster:
        hostname: 'myvcenter01.myhomelab.local'
        username: '{{ test_username }}'
        password: '{{ test_password }}'
        datacenter_name: mydatacenter01
        cluster_name: AnsibleClustertestwithVariable
        validate_certs: no
      delegate_to: localhost
