---
- name: Create Cluster with vmware.vmware
  hosts: myvcenter01.myhomelab.local  # or the appropriate host/group
  gather_facts: no  # Set to yes if you need to gather facts

  tasks:
    - name: Create Cluster with vmware.vmware
      vmware.vmware.cluster:
        hostname: 'myvcenter01.myhomelab.local'
        username: '{{ test_username }}'
        password: '{{ test_password }}'
        datacenter_name: mydatacenter01
        cluster_name: AnsibleClustertestwithVmwareVmware
        validate_certs: no
      delegate_to: localhost
