---
- name: Create VMware Cluster
  hosts: myvcenter01.myhomelab.local  # or the appropriate host/group
  gather_facts: yes  # Set to yes if you need to gather facts

  tasks:
    - name: Create Cluster
      community.vmware.vmware.cluster:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter_name: datacenter
        cluster_name: hellocluster
