---
- name: Gather cluster info from given datacenter
  hosts: myvcenter01.myhomelab.local  # or the appropriate host/group
  gather_facts: no  # Set to yes if you need to gather facts

  tasks:
    - name: GatherBakalim
      community.vmware.vmware_cluster_info:
        hostname: 'myvcenter01.myhomelab.local'
        username: 'administrator@vsphere.local'
        password: 'VMware1!'
        datacenter: mydatacenter01
      delegate_to: localhost
      register: cluster_info
