---
- name: Create Cluster with vmware.vmware
  hosts: myvcenter01.myhomelab.local  # or the appropriate host/group
  gather_facts: no  # Set to yes if you need to gather facts

  tasks:
    - name: Get the health state of applmgmt
      vmware.vmware_rest.appliance_health_applmgmt_info:
        vcenter_hostname: 'myvcenter01.myhomelab.local'
        vcenter_username: '{{ test_username }}'
        vcenter_password: '{{ test_password }}'
        vcenter_validate_certs: no
      delegate_to: localhost
      register: result

    - name: Display vCenter health
      debug:
        var: result


    - name: Get the health state of LOAD INFO
      vmware.vmware_rest.appliance_health_load_info:
        vcenter_hostname: 'myvcenter01.myhomelab.local'
        vcenter_username: '{{ test_username }}'
        vcenter_password: '{{ test_password }}'
        vcenter_validate_certs: no
      delegate_to: localhost
      register: result_LO

    - name: Display vCenter Load health
      debug:
        var: result_LO
        
    - name: Get the health state of MEMORY
      vmware.vmware_rest.appliance_health_mem_info:
        vcenter_hostname: 'myvcenter01.myhomelab.local'
        vcenter_username: '{{ test_username }}'
        vcenter_password: '{{ test_password }}'
        vcenter_validate_certs: no
      delegate_to: localhost
      register: result_MEM

    - name: Display vCenter MEMORY health
      debug:
        var: result_MEM
        
    - name: Get the health state of STORAGE
      vmware.vmware_rest.appliance_health_storage_info:
        vcenter_hostname: 'myvcenter01.myhomelab.local'
        vcenter_username: '{{ test_username }}'
        vcenter_password: '{{ test_password }}'
        vcenter_validate_certs: no
      delegate_to: localhost
      register: result_STORAGE

    - name: Display vCenter MEMORY health
      debug:
        var: result_STORAGE
